/*
LEGACY REFERENCE SCRIPT (FROM ORIGINAL PDF)
===========================================

Source file:
  C:\Users\nic\Downloads\Budget Script.pdf

Purpose:
  - Keep the original legacy logic reference in-repo.
  - Do not edit this file unless you are intentionally updating legacy reference material.

Notes:
  - The canonical original is the PDF above.
  - PDF text extraction can include page markers/line wraps, so this file is intentionally
    treated as a documentation reference rather than a runnable production script.

Legacy identity:
  - Scope default: Account
  - Budget label pattern: "stopped by budget script (Period)"
  - Preview email behavior: sends email with preview banner
  - Legacy re-enable included shopping campaigns/ad groups
*/

function main() {
  throw new Error(
    "legacy_budget_script_reference.js is a reference artifact only. " +
    "Use the active script files for execution."
  );
}

